package kg.kuban.airport.enums;

public enum UserFlightStatus {
    CUSTOMER_BOOKING_FOR_FLIGHT,
    CUSTOMER_BOOKING_DECLINED,
    CUSTOMER_CHECKED,
    CUSTOMER_BRIEFED,
    CUSTOMER_FOOD_DISTRIBUTED,
    CREW_MEMBER_REGISTERED_FOR_FLIGHT,
    CREW_MEMBER_READY,
    ARRIVED
}
