package kg.kuban.airport.enums;

public enum UserFlightsStatus {
    CLIENT_REGISTERED_FOR_FLIGHT,
    CLIENT_REGISTRATION_DECLINED,
    CLIENT_CHECKED,
    CLIENT_BRIEFED,
    CLIENT_FOOD_DISTRIBUTED,
    CREW_MEMBER_REGISTERED_FOR_FLIGHT,
    CREW_MEMBER_READY,
    ARRIVED
}
